### ISSUE TITLE
raganork qr not working

### ISSUE THREAD

**Issue by spio347** [souravkl11/raganork-md#11]
repl.it link and herokuapp link not working

**Comment by souravkl11** [comment]
Hey @spio347, thanks for using this project. Please note that Raganork QR site will be shut down from 22:00 to 06:00 IST inorder to reduce dyno usage.

**Comment by sirajarj** [comment]
> ### _These two reasons may have caused you this problem._
> #### 1. Please note that the Raganork QR site will be shut down from `22:00 to 06:00 IST (Indian standard time)` in order to reduce server dyno usage.
> #### 2. If the site can be opened, and you can't get the QR, you can use the `Fix error` button on the home page
> #### 3. You have got the QR, and can't get session? Connect with me [here](https://wa.me/918921408552?text=Issue:+Can't+get+Raganork+QR+#11)

The number from which the bot was created is suspended from WhatsApp, why and what is the solution
