### ISSUE TITLE
KOYEB UNHEALTHY DEPLOYMENT! 

### ISSUE THREAD

**Issue by condor254** [souravkl11/raganork-md#113]
Great job bro for providing an alternative deployment.. But when I try to deploy, deployment unhealthy and it stops running immediately.. Please fix package.json!or any other help will appreciate 🙏thanks in advance

**Comment by SinethFernando** [comment]
@condor254 , Same here, tried with **Koyeb**, but deployment is unhealthy and is not working as expected.

**Comment by condor254** [comment]
Have you got any solution?

**Comment by SinethFernando** [comment]
No

**Comment by SinethFernando** [comment]
@condor254 , today I tried Deploying to Koyeb, and guess what, **IT WORKED!** Finally a sigh of relief. Check it out!

**Comment by condor254** [comment]
It's working now bro... Happy. But sticker command not working also.pin
command.. Please try fix it

**Comment by souravkl11** [comment]
Fixed
