### ISSUE TITLE
Can it deploy railway

### ISSUE THREAD

**Issue by CP2003** [souravkl11/raganork-md#121]
Can it deploy railway.app ?

**Comment by CP2003** [comment]
> Can it deploy railway.app

**Comment by SinethFernando** [comment]
Railway is one of the easiest ways of deploying the Bot. You can get both the Database and the service from Railway. But the downfall is that they only give you a total of 500 execution hours (approx. 21 days) each month, if you are on the Free trial. If you have a Subscription, then definitely go for Railway.
