### ISSUE TITLE
How to add new language ?

### ISSUE THREAD

**Issue by abdessattar23** [souravkl11/raganork-md#131]
Hello sourav I hope you all right. I want to add a new language to raganork but I don't know how acctually. I hope you will help me 

> I want to add new language to raganork-md

**Comment by souravkl11** [comment]
> Hello sourav I hope you all right. I want to add a new language to raganork but I don't know how acctually. I hope you will help me
> 
> > I want to add new language to raganork-md

make a JSON file similar to english.json in your language. english.json can be found in /plugins/misc/lang folder
contact me on wa here: wa.me/14402225555

**Comment by abdessattar23** [comment]
@souravkl11 but where should I upload it sir, because I have made it.
