### ISSUE TITLE
.clear not working

### ISSUE THREAD

**Issue by byadems** [souravkl11/raganork-md#137]
Why not working?

**Comment by akshitbhatia2004** [comment]
> Why not working?

Yes 🥲🥲

**Comment by akshitbhatia2004** [comment]
> 

@souravkl11 bro please fix clear

**Comment by byadems** [comment]
Module({
    pattern: 'clear group',
    fromMe: false,
    use: 'utility',
  }, (async (message, match) => {
    let messages = await message.group.getMessages();
    for (let msg of messages) {
        await msg.delete();
    }
    await message.send('Group chat has been cleared!');
  }));

Maybe these codes could come in handy.

**Comment by byadems** [comment]
Module({
pattern: 'clear',
fromMe: false,
use: 'utility',
}, (async (message, match) => {
let messages = await message.group.getMessages();
for (let msg of messages) {
await msg.delete();
}
await message.send('Chat has been cleared!');
}));

Maybe these codes could come in handy.

**Comment by akshitbhatia2004** [comment]
> Module({ pattern: 'clear', fromMe: false, use: 'utility', }, (async (message, match) => { let messages = await message.group.getMessages(); for (let msg of messages) { await msg.delete(); } await message.send('Chat has been cleared!'); }));
> 
> Maybe these codes could come in handy.

> But we didn't can add na, only sourav can change it because i did deploy on Docker image

**Comment by byadems** [comment]
Won't you fix it?
