### ISSUE TITLE
The crash problem

### ISSUE THREAD

**Issue by byadems** [souravkl11/raganork-md#147]
Sometimes the bot makes such errors and restarts itself. Is there no definite solution to this problem?

Connected to host server
node:events:505
throw er; // Unhandled 'error' event
^
Error: listen EADDRINUSE: address already in use :::3000
at Server.setupListenHandle [as _listen2] (node:net:1372:16)
at listenInCluster (node:net:1420:12)
at Server.listen (node:net:1508:7)
at _0x5de68c (/rgnk/index.js:1:15663)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Server instance at:
at emitErrorNT (node:net:1399:8)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
code: 'EADDRINUSE',
errno: -98,
syscall: 'listen',
address: '::',
port: 3000
}
raganork-md v3.0.0
Restoring session
Connected to host server
BOT STARTED

**Comment by 20020117** [comment]
I meet the same question,do you solve it?
if you can tell me how to solve it,I will be grateful!

**Comment by souravkl11** [comment]
> Sometimes the bot makes such errors and restarts itself. Is there no definite solution to this problem?
> 
> Connected to host server node:events:505 throw er; // Unhandled 'error' event ^ Error: listen EADDRINUSE: address already in use :::3000 at Server.setupListenHandle [as _listen2] (node:net:1372:16) at listenInCluster (node:net:1420:12) at Server.listen (node:net:1508:7) at _0x5de68c (/rgnk/index.js:1:15663) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) Emitted 'error' event on Server instance at: at emitErrorNT (node:net:1399:8) at processTicksAndRejections (node:internal/process/task_queues:83:21) { code: 'EADDRINUSE', errno: -98, syscall: 'listen', address: '::', port: 3000 } raganork-md v3.0.0 Restoring session Connected to host server BOT STARTED

In your config.env, add:
NO_SERVER:true
