### ISSUE TITLE
Deploy link no longer working via heroku and we also want to support the project

### ISSUE THREAD

**Issue by Maccoder3** [souravkl11/raganork-md#186]
After completing the scanning when l click deploy via heroku ,the link doesnt go through please fix that , plus we want to also contribute towards the project

**Comment by souravkl11** [comment]
> After completing the scanning when l click deploy via heroku ,the link doesnt go through please fix that , plus we want to also contribute towards the project

I've updated the deployment link, check readme! 
You can also contribute to the project, [click here](https://buymeacoffee.com/skl11)

**Comment by Maccoder3** [comment]
No please it's no longer deploying on heroku

**Comment by Maccoder3** [comment]
Hello bro , I've scanned 120 times no session ID I don't kno what's wrong
with raganork  scan link now , please improve it
