### ISSUE TITLE
Vs code

### ISSUE THREAD

**Issue by notmaddy06** [souravkl11/raganork-md#200]
Can you run it using vs code on your system itself like laptop or something if yes just tell me in short how i actually wanna try running it on my system and check the latency

**Comment by David124g** [comment]
It supposed to be WhatsApp based na not normal bot 
It will work on your laptop maybe just not on Vscode

**Comment by chocolaid** [comment]
> Can you run it using vs code on your system itself like a laptop or something if yes just tell me in short how I actually wanna try running it on my system and check the latency

Easy just install nodejs and git on your laptop 

open a folder you'd like to save bot code

and run the installation steps
