### ISSUE TITLE
RAGANORK NOT DEPLOYING IN KOYEB

### ISSUE THREAD

**Issue by Trenchkid254** [souravkl11/raganork-md#211]
![Screenshot_20230917-084533.png](https://github.com/souravkl11/raganork-md/assets/130875277/e044911a-6409-42de-be96-14f39221d499)

**Comment by baduseruyir** [comment]
Deploy the repository by using dockerfile in koyeb. It'll work. Any issues , you can ask me

**Comment by baduseruyir** [comment]
When you are mentioning an error please try to attach the log also
