### ISSUE TITLE
Banned issue souravkl11 please reply this issue

### ISSUE THREAD

**Issue by lufa-official** [souravkl11/raganork-md#215]
Please someone tell me..... Raganork MD Will banned heroku account or not ??

**Comment by souravkl11** [comment]
> Please someone tell me..... Raganork MD Will banned heroku account or not ??

I'll try to patch it soon.

**Comment by byadems** [comment]
Heroku is not as efficient as it used to be. I recommend the Railway to you. You can access the Deploy link via the topic I opened in the issues section.
