### ISSUE TITLE
Need url upload support

### ISSUE THREAD

**Issue by ytdjtjctyghngtdx** [souravkl11/raganork-md#234]
I meant a way to convert links to files

Like telegram url upload bot. I think it can be done with a very small plugin .
Example - https://github.com/souravkl11/raganork-md/blob/main/plugins/youtube.js
It also allows us to get the film.

, thanks...!

**Comment by byadems** [comment]
Are you talking about the transmission of video files as files?

**Comment by badu-ser** [comment]
He means that a plugin to download files from a url. 
Eg: giving t.me/sjjdjdjjd {a telegram video/file link) should return the actual file in WhatsApp.

**Comment by badu-ser** [comment]
A downloader from url

**Comment by byadems** [comment]
The infrastructure of each file hosting site is different, so let's give an example for Turbobit if a module is created. It works for Turbobit, but Yandex will give an error for Disk. I don't think it's a very necessary thing. The boat has a limited capacity. It may create problems in the future.

**Comment by darkdeathoriginal** [comment]
you can already do this for images and videos by using `upload` command.

**Comment by byadems** [comment]
> you can already do this for images and videos by using `upload` command.

No, he's talking about downloading.

**Comment by darkdeathoriginal** [comment]
> No, he's talking about downloading.

`upload` commands downloads from url.

**Comment by ytdjtjctyghngtdx** [comment]
> Are you talking about the transmission of video files as files?

No 
![Screenshot_20240121_142544_Telegram](https://github.com/souravkl11/raganork-md/assets/94878796/c75bd463-e2ee-40e8-995d-414eb95298f9)

I'm talking about something like this

**Comment by ytdjtjctyghngtdx** [comment]
> > No, he's talking about downloading.
> 
> `upload` commands downloads from url.

It is limited to a few Mb

**Comment by darkdeathoriginal** [comment]
> It is limited to a few Mb
limit is there becouse koyeb and heroku crashes on large files.

**Comment by darkdeathoriginal** [comment]
You can always create your own custom plugin if you want.

**Comment by byadems** [comment]
Yes, it seems possible, but WhatsApp does not even allow a 10-minute video. However, it can be sent as a file, which is still limited.

**Comment by darkdeathoriginal** [comment]
> Yes, it seems possible, but WhatsApp does not even allow a 10-minute video. However, it can be sent as a file, which is still limited.

i have sent a video with more than 1 hour duration. Whatsapp doesn't have duration limit it only has size limit. Any media can only have maximum of 100mb but document can have 2gb of size.

**Comment by byadems** [comment]
Currently, only one Railway is currently running smoothly, and its storage is limited to 1 GB. That's why the process is a little challenging.

**Comment by ytdjtjctyghngtdx** [comment]
> > Yes, it seems possible, but WhatsApp does not even allow a 10-minute video. However, it can be sent as a file, which is still limited.
> 
> i have sent a video with more than 1 hour duration. Whatsapp doesn't have duration limit it only has size limit. Any media can only have maximum of 100mb but document can have 2gb of size.

He said it is true, but we can put it as a file.

**Comment by ytdjtjctyghngtdx** [comment]
> Currently, only one Railway is currently running smoothly, and its storage is limited to 1 GB. That's why the process is a little challenging.

It's okay, friend, there were people who made bots using vps 

https://github.com/souravkl11/raganork-md/issues/234#issuecomment-1929276894

If we do this, we will not have a problem.

 thank you

**Comment by souravkl11** [comment]
As mentioned by @darkdeathoriginal, the `upload` command does the fetching of various file types, enabling users to fetch and download content from a URL and share it via WhatsApp as a document message. However, the file size limit is contingent upon the hosting environment's resources, including memory allocation, bandwidth, and server specifications. And remember, WhatsApp isn't Telegram 😕
