### ISSUE TITLE
Critical Instagram Update

### ISSUE THREAD

**Issue by byadems** [souravkl11/raganork-md#242]
Hi buddy, your last update caused the following error while trying to download an Instagram post. Let you know.

```
(node:7) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by souravkl11** [comment]
> Hi buddy, your last update caused the following error while trying to download an Instagram post. Let you know.
> 
> ```
> (node:7) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
> 
> (Use `node --trace-warnings ...` to show where the warning was created)
> ```

When does the issue occur?
What command did you use?
Was the command successful?

**Comment by byadems** [comment]
If you type the following command into the bot, it is likely that you will encounter the problem I mentioned directly.

`.insta https://www.instagram.com/p/C3TE562NDDl/?igsh=MTVhdHFzZTB1ZTRsMw==`

SS: https://prnt.sc/MSGzAOxVhlVx

**Comment by souravkl11** [comment]
The log you provided, it's a warning, not an ERROR!!
The ss you provided, it's coz that post may not be supported, try another one. 
Issues aren't the place for simply reporting something without retrying to rectify the problem caused the error using different approaches.
