### ISSUE TITLE
Warning Module Error ⚠️

### ISSUE THREAD

**Issue by byadems** [souravkl11/raganork-md#243]
Hi buddy, I've been trying to pull up a user's current alerts with the getWarn function in the alert module for a long time, but the result returns as NaN. I checked your library, chat and user variables are defined. Where exactly could the problem be?

> Module({
    pattern: 'getwarn ?(.*)',
    use: 'group',
    fromMe: false,
    desc: 'Get Warning.'
}, async (m, mat) => {
    let adminAccessValidated = ADMIN_ACCESS ? await isAdmin(m, m.sender) : false;
    if (m.fromOwner || adminAccessValidated) {
        var user = m.mention[0] || m.reply_message.jid
        if (!user) return await m.sendReply(Langs.NEED_USER)
        if (!m.jid.endsWith('@g.us')) return await m.sendReply(Langs.GROUP_COMMAND)
        try {
            var warnings = await getWarn(m.jid, user)
            console.log("Warning:", warnings);
            var warns = warnings.length
            if (warns === 0) {
                return await m.client.sendMessage(chat,'```User @'+user.split('@')[0]+ ' is not in the warn list ✅```', MessageType.text, { quoted: m.data, contextInfo: { mentionedJid: [user] } })    
            } else {
                var total = parseInt(WARN) - warns
                return await m.client.sendMessage(chat,'```User @'+user.split('@')[0]+' has only ('+total+') warnings left ⚠```', MessageType.text, { quoted: m.data, contextInfo: { mentionedJid: [user] } })    
            }
        } catch {
            return await m.sendReply("Error.")
        }
    }
});

**Comment by byadems** [comment]
@souravkl11

**Comment by souravkl11** [comment]
Invalid issue. Issues related to the official plugins shall only be opened.
