### ISSUE TITLE
BOT ISSUE

### ISSUE THREAD

**Issue by blooper-ser** [souravkl11/raganork-md#26]
Heroku Accnt Suspend Akunnu

**Comment by souravkl11** [comment]
> Heroku Accnt Suspend Akunnu

You should read heroku terms & policies before creating an account on heroku

**Comment by blooper-ser** [comment]
> > Heroku Accnt Suspend Akunnu
> 
> You should read heroku terms & policies before creating an account on heroku

Njn Raganork Bot Nere Deploy Chythitulu , Vere Onum Chythitila

**Comment by aswinkunjuzz** [comment]
Active annu pashe kodukunna command s nu reply ella
