### ISSUE TITLE
Install  raganork-md on vps

### ISSUE THREAD

**Issue by Alcoders-official** [souravkl11/raganork-md#44]
Install  raganork-md on vps

**Comment by pingvicky** [comment]
![IMG-20220803-WA0281](https://user-images.githubusercontent.com/110294505/182543975-77218cff-4ae6-4df7-9937-d1f43efd8bba.jpg)

**Comment by pingvicky** [comment]
![IMG-20220803-WA0281](https://user-images.githubusercontent.com/110294505/182544040-dc9e565a-fe75-4e1b-9e0b-90da8337934f.jpg)

**Comment by pingvicky** [comment]
![IMG-20220803-WA0281](https://user-images.githubusercontent.com/110294505/182544040-dc9e565a-fe75-4e1b-9e0b-90da8337934f.jpg

**Comment by pingvicky** [comment]
![IMG-20220803-WA0281](https://user-images.githubusercontent.com/110294505/182544040-dc9e565a-fe-4e1b-9e0b-90da8337934f.jpg
