### ISSUE TITLE
How to Delete Filters that are already set for a Group or Contact?

### ISSUE THREAD

**Issue by SinethFernando** [souravkl11/raganork-md#47]
Thank you so much @souravkl11 for telling me the format to set a Filter! It works like a charm! Can I also know how to **delete a Filter** Just in case if required?
I accidently added an unwanted filter to a contact and now it always send the Filter message for each and every message that I type and it is annoying me. Please help!
Thank you!

_Originally posted by @SinethFernando in https://github.com/souravkl11/raganork-md/issues/39#issuecomment-1193062784_

**Comment by souravkl11** [comment]
Use `.stop <filter>`
Refer to command lists for more.

**Comment by SinethFernando** [comment]
Thank you so much! It worked!
