### ISSUE TITLE
Mention Bgm Issue 

### ISSUE THREAD

**Issue by RAFI-SER** [souravkl11/raganork-md#58]
Error on parsing audio 
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

When I Mention The Sudo Userss Bot Sending This Message How To Fix It Or Please Fix That Plugin Vrohh

**Comment by souravkl11** [comment]
> Error on parsing audio TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
> 
> When I Mention The Sudo Userss Bot Sending This Message How To Fix It Or Please Fix That Plugin Vrohh

You should properly fill the AUDIO_DATA var
