### ISSUE TITLE
Instagram 

### ISSUE THREAD

**Issue by zZyreXx** [souravkl11/raganork-md#78]
Insta photo post error ahne not loading showing like vedios and not opening.

**Comment by NITHEESHNS** [comment]
![Uploading +1 (914) 300-1271 20220829_162412.jpg…]()

**Comment by NITHEESHNS** [comment]
![+1 (914) 300-1271 20220829_162412](https://user-images.githubusercontent.com/107642115/187224767-c02c3601-05aa-4add-9b27-0adbe369a16c.jpg)

**Comment by zZyreXx** [comment]
insta story command also not working
